create database customer_behaviour;
use customer_behaviour;
select * from customer limit 5;
#Q1. What is the total revenue generated by male vs. female customers?

select gender, SUM(purchase_amount) as revenue 
from customer
group by gender;

#Q2. Which customers used a discount but still spent more than the average purchase amount ?

SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
    SELECT AVG(purchase_amount)
    FROM customer
  );


#Q3. Which are the top 5 products with the highest average review rating?

select item_purchased , round(avg(review_rating),2)as "Average product rating" 
from customer 
group by item_purchased
order by avg(review_rating) desc
limit 5;
#Q4. Compare the average Purchase Anounts between Standard and Express Shipping.
select shipping_type,
round(AVG(purchase_amount),2)
from customer 
where shipping_type in ("Standard" , "Express")
group by shipping_type;

#QS. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status ,
count(customer_id) as total_customers,
AVG(purchase_amount) as "Average purchased Amount",
SUM(purchase_amount) as "Total Revenue"
from customer 
group by subscription_status;

#Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*)*100, 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;



#Q7. Segment customers into New, Returning, and Loyal based on their previous purchases, and show the count of each segment.

WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment, 
    COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;



#Q8. Are customer who are repeat subscribe?(more than 5 previous purchase) also likely to subscribe  ?

SELECT 
    subscription_status,
    COUNT(*) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

#Q9 what is  the revenue contribution of each age group?
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;


